#!/usr/bin/env ruby
puts "rock rock rock"
$stdout.flush
while command = gets
  command = command.strip
  if command == "next"
    puts "rock"
  elsif command == "done"
    puts "okay"
    break
  end
  $stdout.flush
end
