#!/usr/bin/env ruby
puts "randombot"
$stdout.flush
while command = gets
  command = command.strip
  if command == "next"
    puts %w{rock paper scissors}.sample
  elsif command == "done"
    puts "okay"
    break
  end
  $stdout.flush
end
